spring:
  datasource:
    url: jdbc:h2:mem:schedule
    username: go-user
    password: go-user!
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generateDdl: false
    hibernate:
      ddlAuto: none
